// Generated by gencpp from file exam_ros_msg/wxy_msg.msg
// DO NOT EDIT!


#ifndef EXAM_ROS_MSG_MESSAGE_WXY_MSG_H
#define EXAM_ROS_MSG_MESSAGE_WXY_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exam_ros_msg
{
template <class ContainerAllocator>
struct wxy_msg_
{
  typedef wxy_msg_<ContainerAllocator> Type;

  wxy_msg_()
    : x(0)
    , y(0)
    , z(0)
    , test(0.0)  {
    }
  wxy_msg_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , z(0)
    , test(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _z_type;
  _z_type z;

   typedef double _test_type;
  _test_type test;





  typedef boost::shared_ptr< ::exam_ros_msg::wxy_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exam_ros_msg::wxy_msg_<ContainerAllocator> const> ConstPtr;

}; // struct wxy_msg_

typedef ::exam_ros_msg::wxy_msg_<std::allocator<void> > wxy_msg;

typedef boost::shared_ptr< ::exam_ros_msg::wxy_msg > wxy_msgPtr;
typedef boost::shared_ptr< ::exam_ros_msg::wxy_msg const> wxy_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exam_ros_msg::wxy_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exam_ros_msg::wxy_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exam_ros_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'exam_ros_msg': ['/home/free/catkin_kinect2/src/exam_ros_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exam_ros_msg::wxy_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exam_ros_msg::wxy_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exam_ros_msg::wxy_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exam_ros_msg::wxy_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exam_ros_msg::wxy_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exam_ros_msg::wxy_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exam_ros_msg::wxy_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f139c3f78860af338da979db6c5e8601";
  }

  static const char* value(const ::exam_ros_msg::wxy_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf139c3f78860af33ULL;
  static const uint64_t static_value2 = 0x8da979db6c5e8601ULL;
};

template<class ContainerAllocator>
struct DataType< ::exam_ros_msg::wxy_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exam_ros_msg/wxy_msg";
  }

  static const char* value(const ::exam_ros_msg::wxy_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exam_ros_msg::wxy_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n\
int32 y\n\
int32 z\n\
float64 test\n\
";
  }

  static const char* value(const ::exam_ros_msg::wxy_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exam_ros_msg::wxy_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.test);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wxy_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exam_ros_msg::wxy_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exam_ros_msg::wxy_msg_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.z);
    s << indent << "test: ";
    Printer<double>::stream(s, indent + "  ", v.test);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXAM_ROS_MSG_MESSAGE_WXY_MSG_H
